# Generated by Django 5.1.3 on 2025-10-21 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qrgenerator', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='code',
            name='secure_index',
            field=models.CharField(default=None, max_length=64, unique=True),
        ),
    ]
