# Generated by Django 5.1.3 on 2025-10-29 20:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('qrgenerator', '0002_code_secure_index'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='code',
            options={'permissions': [('can_verify_qr', 'Can verify QR codes')]},
        ),
        migrations.AlterModelOptions(
            name='codebatch',
            options={'permissions': [('can_generate_qr', 'Can generate QR codes'), ('can_verify_qr', 'Can verify QR codes')]},
        ),
    ]
