# Generated by Django 5.1.3 on 2025-10-29 21:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='max_qr_codes',
            field=models.IntegerField(default=100),
        ),
        migrations.AddField(
            model_name='customuser',
            name='owner',
            field=models.ForeignKey(blank=True, limit_choices_to={'role': 'owner'}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='verifier_accounts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('owner', 'Account Owner'), ('verifier', 'Verifier Bot')], default='verifier', max_length=20),
        ),
    ]
