# Generated by Django 5.1.3 on 2025-10-29 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_customuser_max_qr_codes_customuser_owner_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('owner', 'Account Owner'), ('verifier', 'Verifier Bot')], default='owner', max_length=20),
        ),
    ]
