# Generated by Django 5.1.3 on 2025-10-29 23:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_customuser_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='max_qr_codes',
            field=models.IntegerField(default=100, verbose_name='Limite de QR codes'),
        ),
    ]
