# Generated by Django 5.1.3 on 2025-10-30 10:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_customuser_max_qr_codes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='max_qr_codes',
        ),
        migrations.AlterField(
            model_name='customuser',
            name='owner',
            field=models.ForeignKey(blank=True, limit_choices_to={'role': 'owner'}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='verifiers', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('admin', 'Administrator'), ('owner', 'QR Code Owner'), ('verifier', 'QR Verifier')], default='owner', max_length=20),
        ),
    ]
